FROM ruby:3.2.2-slim

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install -y build-essential sqlite3 libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app
# Copy Gemfile and install dependencies
COPY Gemfile Gemfile.lock ./
RUN bundle install

RUN mkdir -p app/db && chmod 777 app/db   
RUN ls -la app

COPY . .
RUN ls -la app

# Application code will be mounted at runtime
ENV RACK_ENV=development
ENV PORT=8080

# RUN bundle exec rake db:migrate

CMD ["bundle", "exec", "rackup", "--host", "0.0.0.0", "-p", "8080"] 