development:
  adapter: sqlite3
  database: <%= ENV['DATABASE_PATH'] || 'db/development.sqlite3' %>

production:
  adapter: sqlite3
  database: <%= ENV['DATABASE_PATH'] || 'db/production.sqlite3' %>

